services:
  worker:
    build: .
    container_name: cf_worker_env
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment: 
      NODE_ENV: development
      PGHOST: postgres
      PGUSER: postgres_user
      PGPASSWORD: pw111223#
      PGDATABASE: appdb
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: cf_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: pw111223#
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: